mwApis:
  # This is the only required parameter,
  # the URL of you MediaWiki API endpoint.
  uri: 'https://DOMAIN_HERE/api.php'
  # The "domain" is used for communication with Visual Editor
  # and RESTBase.  It defaults to the hostname portion of
  # the `uri` property above, but you can manually set it
  # to an arbitrary string.
  domain: 'DOMAIN_HERE'  # optional